var seekerDropDownListController = require("../controllers/seekerDropDownList");
var drop = new seekerDropDownListController();
var express = require("express");
var router = express.Router();
var auth = require("../auth/auth");

const cloudinary = require('cloudinary').v2;
const { CloudinaryStorage } = require('multer-storage-cloudinary');
const multer = require('multer');
 
const app = express();


router.post("/addDescribe", auth, drop.addDescribe);
router.post("/allDescribeDetail", auth, drop.allDescribeDetail);
router.post("/addlooking", auth, drop.addlooking);
router.post('/allLookingDetail', auth , drop.allLookingDetail);
router.post('/addlanguage', auth, drop.addlanguage);
router.post('/allLanguageDetail',auth,drop.allLanguageDetail);
router.post('/addproficiency',auth,drop.addproficiency);
router.post('/allProficiencyDetail',auth,drop.allProficiencyDetail);
router.post('/addExperienceYear',auth,drop.addExperienceYear);
router.post('/allExperienceYearDetail',auth,drop.allExperienceYearDetail);
router.post('/addClientIndustry',auth,drop.addClientIndustry);
router.post('/allClientIndustry',auth,drop.allClientIndustry);
router.post('/addService',auth,drop.addService);
router.post('/allServiceDetail',auth,drop.allServiceDetail);
router.post('/addPrefferedSelling',auth,drop.addPrefferedSelling);
router.post('/allPrefferedSellingDetail',auth,drop.allPrefferedSellingDetail);
router.post('/addAverageDeal',auth,drop.addAverageDeal);
router.post('/allAverageDealDetail',auth,drop.allAverageDealDetail);
router.post('/addAverageDealValue',auth,drop.addAverageDealValue);
router.post('/allAverageDealValueDetail',auth,drop.allAverageDealValueDetail);
router.post('/addHighestDegree',auth,drop.addHighestDegree);
router.post('/allHighestDegreeDetail',auth,drop.allHighestDegreeDetail);
router.post('/addSize',auth,drop.addSize);
router.post('/allSizeDetail',auth,drop.allSizeDetail);
router.post('/addFunction',auth,drop.addFunction);
router.post('/allFunctionDetail',auth,drop.allFunctionDetail);
router.post('/addSeniority',auth,drop.addSeniority);
router.post('/allSeniorityDetail',auth,drop.allSeniorityDetail);
router.post('/addRegion',auth,drop.addRegion);
router.post('/allRegionDetail',auth,drop.allRegionDetail);
router.post('/addCurrency',auth,drop.addCurrency);
router.post('/allCurrencyDetail',auth,drop.allCurrencyDetail);
router.post('/addRepeatCustomerSpend',auth,drop.addRepeatCustomerSpend);
router.post('/allRepeatCustomerSpend',auth,drop.allRepeatCustomerSpend);
router.post('/addContinentDetail',auth,drop.addContinentDetail);
router.post('/allContinentDetail',auth,drop.allContinentDetail);
router.post('/allCountryDetail',auth,drop.allCountryDetail);
router.post('/allContinentDetailForSelectedCountry',auth,drop.allContinentDetailForSelectedCountry);
/////////business///
router.post('/addOperationYear',auth,drop.addOperationYear);
router.post('/allOperationYear',auth,drop.allOperationYear);
router.post('/addRevenueRange',auth,drop.addRevenueRange);
router.post('/allRevenueRange',auth,drop.allRevenueRange);
router.post('/addCompanySize',auth,drop.addCompanySize);
router.post('/allCompanySize',auth,drop.allCompanySize);
router.post('/addNumOfCustomer',auth,drop.addNumOfCustomer);
router.post('/allNumOfCustomer',auth,drop.allNumOfCustomer);
router.post('/addAverageSaleCycle',auth,drop.addAverageSaleCycle);
router.post('/allAverageSaleCycle',auth,drop.allAverageSaleCycle);
router.post('/addCustomerSpend',auth,drop.addCustomerSpend);
router.post('/allCustomerSpend',auth,drop.allCustomerSpend);
router.post('/addSellingArea',auth,drop.addSellingArea);
router.post('/allSellingAreaDetail',auth,drop.allSellingAreaDetail);
router.post('/addPaymentOption',auth,drop.addPaymentOption);
router.post('/allPaymentOptionDetail',auth,drop.allPaymentOptionDetail);
router.post('/addRegionForBusiness',auth,drop.addRegionForBusiness);
router.post('/allRegionForBusinessDetail',auth,drop.allRegionForBusinessDetail);
router.post('/filterForBusinessDropDown',auth,drop.filterForBusinessDropDown);
router.post('/filterForSeekerDropDown',auth,drop.filterForSeekerDropDown);
router.post('/allServiceDetailForBusiness',auth,drop.allServiceDetailForBusiness);
router.post('/allServiceDetailForFilter',auth,drop.allServiceDetailForFilter);
router.post('/allServiceDetailForBusinessChange',auth,drop.allServiceDetailForBusinessChange);
router.post('/allClientIndustryBusiness',auth,drop.allClientIndustryBusiness);
router.post('/allServiceDetailBusiness',auth,drop.allServiceDetailBusiness);
router.post('/allServiceDetailBusinessForIndustryNetwork',auth,drop.allServiceDetailBusinessForIndustryNetwork);
router.post('/createIndustry',drop.createIndustry);
router.post('/changeDAta',drop.changeDAta);
module.exports = router;
